// Config plugin (G2-33): keep the on-device health-data mirror out of
// iCloud/iTunes device backups.
//
// expo-sqlite's default database directory on iOS is
// Documents/SQLite/<name>.db, and Documents is included in the standard
// device backup. Apple Guideline 5.1.3(ii) is normally read as barring
// iCloud/CloudKit as your *storage*, and whether an ordinary encrypted device
// backup falls inside that is genuinely ambiguous — this is prudent hygiene,
// not a confirmed violation.
//
// Deliberately NOT solved by opening the database in Library/Caches instead:
// that directory can be purged by the OS under storage pressure, and
// pending_writes (the user's own edits, queued but not yet reached the
// server — see src/lib/db/client.ts) is the one thing in the mirror that
// sync cannot recover if lost. Marking the existing Documents/SQLite files as
// excluded-from-backup (NSURLIsExcludedFromBackupKey) gets the same result
// without that risk.
//
// This has to be a config plugin rather than a hand-edit of
// ios/halmoni/AppDelegate.swift because that file is regenerated by
// `expo prebuild` (the ios/ directory is gitignored — see eas.json) and any
// direct edit would be silently lost on the next EAS build.

const { withAppDelegate } = require('expo/config-plugins');

const MARKER = 'halmoni-exclude-sqlite-from-backup (G2-33)';

function swiftSnippet() {
  return `
    // ${MARKER}
    // Runs on every launch; cheap and idempotent for one small file, and it
    // has to re-run because expo-sqlite recreates the file the first time a
    // fresh install opens the database.
    do {
      let fm = FileManager.default
      if let docs = fm.urls(for: .documentDirectory, in: .userDomainMask).first {
        let sqliteDir = docs.appendingPathComponent("SQLite")
        if let names = try? fm.contentsOfDirectory(atPath: sqliteDir.path) {
          for name in names where name.hasPrefix("halmoni.db") {
            var fileURL = sqliteDir.appendingPathComponent(name)
            var values = URLResourceValues()
            values.isExcludedFromBackup = true
            try? fileURL.setResourceValues(values)
          }
        }
      }
    }
`;
}

module.exports = function withExcludeSqliteFromBackup(config) {
  return withAppDelegate(config, (config) => {
    const { modResults } = config;
    if (modResults.language !== 'swift') {
      throw new Error(
        'withExcludeSqliteFromBackup expects a Swift AppDelegate (got ' + modResults.language + ')',
      );
    }
    if (modResults.contents.includes(MARKER)) {
      return config; // already applied (re-running prebuild)
    }

    const anchor = 'reactNativeFactory = factory';
    const anchorIdx = modResults.contents.indexOf(anchor);
    if (anchorIdx === -1) {
      throw new Error(
        'withExcludeSqliteFromBackup: could not find the expected anchor line in AppDelegate.swift — ' +
          'the Expo-generated template has likely changed shape and this plugin needs updating',
      );
    }
    const insertAt = modResults.contents.indexOf('\n', anchorIdx) + 1;
    modResults.contents =
      modResults.contents.slice(0, insertAt) +
      swiftSnippet() +
      modResults.contents.slice(insertAt);

    return config;
  });
};
